### PR TITLE
Documenting Acorn

### PR DESCRIPTION
**Pull request by TobyLobster**
This change allows commentary to be added automatically around calls to all the remaining OSBYTE calls, and adds commentary for all the other OS calls OSWORD, OSFILE, OSARGS, OSGBPB etc.
Use of a register after exiting one of these routines is now commented with the register's meaning where applicable.
The `on_exit` section of `subroutine()` call is also used to add these comments for regular subroutines. Bracketed comments like '(preserved)' are not added.

Added `no_automatic_comment(addr)` to disable specific automatic commentary at an address if desired.

Added `auto_comment()` which is for use by acorn.py and other future automatic commenters. It is like `comment()`, but doesn't comment if the address in question is either outside the binary, or has been disabled using `no_automatic_comment()`. The address can be outside the binary in cases like OSWORD, where the data block can be anywhere in memory.  Optionally, a blank line can be added too.

Reduced the number of ASSERTs a little by not outputting duplicates.

### CODE REVIEW

**Comment by TobyLobster** [comment]
This implements the remainder of #18.

**Comment by ZornsLemma** [comment]
Very nice work Toby - I'm impressed by the way you're even interpreting the VDU variable numbers! The special test case you've added obviously shows everything off, but it's looking at the diffs for example disassemblies of real code which just happen to be improved by this that really shows off the potential, I think.

Are you going to post to stardot about this? It might be worth pointing out explicitly that as well as benefitting disassemblies for code using the OS, people can teach py8dis about subroutines in the code they're disassembling and get the same benefits. Having register use commented automatically before/after subroutine calls feels somewhat magical. :-)

I think it would be a nice extension to what you've done (and probably easy, in isolated cases) to add automatic expr() use, so that:

lda #64
jsr osfind ; open file for input (A=64)

can be turned into

osfind_open_input = 64
...
lda #osfind_open_input
jsr osfind ; open file for input (A=64)

Does this seem reasonable in principle? If it does I'll raise an issue to track this as a potential improvement.

I've merged this to master, can you please give it a quick sanity check? I got some merge conflicts which I think were just my ineptitude with git but it's just possible I screwed up badly...

**Comment by TobyLobster** [comment]
>Does this seem reasonable in principle? 

Yes, there are probably just a few cases of this. One minor limitation is we can't define constants in terms of other constants e.g. `osfind_open_read_write = osfind_open_read | osfind_open_write`

I say minor because (a) it doesn't happen often and (b) it doesn't actually limit our ability to define constants.

Note also that BeebAsm uses `OR` where other assemblers use the vertical bar `|`. A cross assembly way to define expressions in general (not just for constants) feels like it would be weird. Perhaps it might consist of calls like `expr=or(expr1, expr2)` where the `expr` variables are strings?

One thing I found I couldn't handle completely is that a few OS calls return success in carry e.g. OSGBPB. If we allow on_exit to track {'c' : "set if the transfer could not be completed" } then we could label a post-exit use of C e.g. a BCS instruction. Each opcode would have to know which flags it used and set, similarly to how we annotate register use for each opcode now. ADC would both use C and overwrite C, for instance.

I'm thinking we could detect and comment on these instructions:
`SEI     ; disable interrupts`
`CLI    ; enable interrupts`

Can we detect specific memory mapped IO read/writes and interpret them?

> I've merged this to master, can you please give it a quick sanity check?

Looks good.

**Comment by ZornsLemma** [comment]
Thanks for checking the merge, I'm glad it looks OK!

What you say here generally seems sensible.

I think your suggested way of handling the variable "or" is reasonable; we could instead have a "constant" which is " OR " for beebasm or " | " for other assemblers and build up "or" expressions using string concatenation, but using a function feels cleaner.

Tracking the state of C seems logical, although once we go there it might make sense to start tracking Z as well (the OS may not do it, but I know I've written subroutines which return state in Z), and then perhaps V (which is at least modified by very few instructions). I certainly don't have any objections in principle to this.

I don't particularly object to auto-commenting on SEI/CLI/PHP/PLP, but it feels a little odd - these are standard 6502 instructions which I'd expect the user to understand. As I say, I don't particularly object if you'd like to add this, although it should probably be optional. FWIW commenting SEI/CLI feels a little more natural, as it's maybe not so easy to remember whether I set means "allow interrupts" or "don't allow interrupts", whereas PHP/PLP feel more like "ordinary" instructions whose mnemonics are fairly self-explanatory to me.

I think we could detect memory mapped I/O read/writes - didn't we previously discuss doing this for CRTC registers, for example? I haven't thought too much about what the code would look like, but I guess we'd kind of want to process loads/stores of these addresses as a kind of pseudo-subroutine call, although we might well register them via a new function instead of subroutine(). Obviously lots more instructions could trigger this hook, but that's probably not a big deal in practice.

**Pull request merged**
