### PR TITLE
Support for 8080 code

### PR DESCRIPTION
**Pull request by TobyLobster**
* Filled in all the 8080 opcodes
* Output in a format suitable for the z88dk-z80asm assembler in 8080 mode (as part of the z88dk, https://z88dk.org/site/)
* Added an example binary and python file to disassemble (from http://www.emulator101.com/full-8080-emulation.html) which tests all 8080 instructions.

### CODE REVIEW

**Comment by ZornsLemma** [comment]
Thanks Toby, that's very cool! I've merged this, should I also delete the comment from the top of cpu8080.py saying this is a skeleton?

Do you think we should default to a suitable assembler (i.e. z88dk) if trace8080.py is included rather than leaving beebasm selected? I don't think this is a big deal but I could see arguments for and against.

**Comment by TobyLobster** [comment]
>"should I also delete the comment"

Sure, that makes sense.

>"Do you think we should default to a suitable assembler"

I'm leaning slightly towards leaving them independent.

**Comment by ZornsLemma** [comment]
I've pushed a change to delete that comment. Since it's less work to leave the assembler and target CPU completely independent, let's go with that. (I half wonder if the default to beebasm should be removed, but it's probably best to stick with it.)

**Comment by TobyLobster** [comment]
Some further thoughts for consideration:

* The assembler files (e.g. acme.py) could have a property returning the list of CPUs it supports. (e.g. acme gives ["6502", "65C02"]; z88dk returns ["8080", "z80"] etc). Perhaps an enum would help.
* The load() function could take a new parameter specifying the CPU required to disassemble the binary file. (This would replace the 'import trace6502' method of doing things).
* The assembler would still be specified on the command line as now unchanged.
* The program could then properly report if an unsupported combination is chosen.
* The assemblers should more neatly be classes, since they share some kind of interface.

**Comment by ZornsLemma** [comment]
This seems like a reasonable approach on the whole. The only thing that slightly worries me is adding the CPU parameter to load() instead of using "import tracefoo":
* Is this going to cause problems if the user wants to load() multiple files? It's not likely to be a big deal, but it would then be possible to select multiple CPU types, which probably isn't going to work as the user wants. (Then again, they can already get into a mess by importing multiple tracefoo modules.)
* Is this going to make it harder for a user to add their own custom variant of a CPUif they want to? I'm speculating generally here so I don't have a specific example in mind, but if someone currently wants to fork trace6502.py as trace6502withhacksformycase.py they can do that and just import it, but if we start adding an enum or similar they they need to wire their code into the framework so load() knows how to handle it, or they will have to just hack trace6502.py "in place".
I don't think these are critical problems, I just wanted to jot these thoughts down.

**Comment by TobyLobster** [comment]
Yes, good points. To add some further thoughts that occur in response:

On the first point, (a) the common use case is to load one file I imagine (so this wouldn't be an issue for most users), and (b) we can always give a nice error message if the CPU supplied on subsequent loads doesn't match the first load.

One reason I like the idea is because the user is explicitly saying e.g. "this binary is for the 6502" - there is a definitive and solid connection between the binary and the CPU it is designed to run on, so I like that 1-1 connection. Making the user be explicit about that is clean and tidy.

Perhaps in a long distant theoretical future where the code base is reworked to be super shiny, a single python control file could execute multiple go() passes across multiple files and CPUs etc... But not right now.

The second bullet point is interesting. The tracefoo files are very small - they only import the appropriate Cpu class and instantiate it.

So users could write their own CpuFooWithHacks class (e.g. by copying Cpu6502 and futzing with it) then call load() passing a singleton instance of that class instead of the cpu name. load() would look at the cpu parameter and if it's our enum type then it is a Cpu that is already found in the framework that we can instance. Otherwise if it's an instance of class Cpu then it would use that instance instead.

Then if at some point CpuFooWithHacks became popular/useful we could incorporate it into the library of known Cpus in a future release adding it to the enum.

**Comment by ZornsLemma** [comment]
I like the idea of making the explicit connection between the binary and the CPU it is designed for, and the idea of passing in a singleton instance to load() handles the (entirely theoretical at the moment) case of CpuFooWithHacks.

Do you plan to implement this in the near future? I only ask because if you don't, we should perhaps create a new issue and summarise/copy some of the content from this discussion there, as this closed PR would be easy to overlook in future. (We could re-open the PR, but because it has been merged I think it would be confusing to do that.)

**Comment by TobyLobster** [comment]
If you could create a new issue that would be great, I have other things that need my attention for the moment so am not likely to implement this very soon. I'd like to come back at some time in the not far future though, as I've enjoyed working on this.

**Comment by ZornsLemma** [comment]
Thanks Toby, I've raised https://github.com/ZornsLemma/py8dis/issues/8 with a link back here for the full discussion. Good luck with the other things and I'm glad you've enjoyed work on py8dis, it's been really good to see your contributions.

**Pull request merged**
