### PR TITLE
Fix for singleton / 65C02 issue

### PR DESCRIPTION
**Pull request by TobyLobster**
* Moves the cpu classes into separate files, so they can import from each other without instantiating any Cpu objects.
* The trace[CPU].py files are just to instantiate the relevant cpu class.

### CODE REVIEW

**Comment by ZornsLemma** [comment]
Thanks Toby, that's a nice fix and I've merged it.

I do wonder if hook_subroutine from trace6502.py should be copied into trace65c02.py or otherwise moved, but that's not a big deal - perhaps easiest to wait until something breaks!

**Comment by TobyLobster** [comment]
Yes, it should probably go in commands.py, since it is a command.

**Comment by ZornsLemma** [comment]
Thanks Toby, that's a good suggestion. I made the change before I saw your edit. Since it's easy to fix once you know and py8dis is still in flux I'm personally inclined not to worry too much about this, but it's a valid point. Do you think we should put a compatibility shim back in?

**Comment by ZornsLemma** [comment]
Incidentally, I did note that if you don't "import traceSOMECPU", you can get confusing errors because trace.cpu is None. You can see this by deleting "import trace6502" from the top of anfs418.py, for example.

My initial thought is to make "cpu" a property so we can add some code and call die() with a nice error message if it's None, while still making it look like a regular variable, but perhaps that's overkill - do you have any other thoughts?

**Comment by TobyLobster** [comment]
>"Do you think we should put a compatibility shim back in?"
No, I'm happy to let it evolve as needed.
>"My initial thought is to make "cpu" a property so we can add some code and call die() with a nice error message if it's None, while still making it look like a regular variable"
That sounds good to me.

**Comment by ZornsLemma** [comment]
Let's not worry about compatibility then, if someone complains we can always revisit this. :-)

Unfortunately I spoke too soon, trace is not a class so we "can't" make trace.cpu a property. ("can't" in quotes because I got lost in the weeds investigating this on StackExchange and gave up; I don't think it's a good idea to get overly clever for such a trivial feature, but it may be possible.)

Instead I've put a check in the load() function, which should be a fairly safe place to check this in practice. Let me know if you think there's a better way to do this of course!

**Pull request merged**
