### PR TITLE
Substitute constants analysis

### PR DESCRIPTION
**Pull request by TobyLobster**
* Implements `substitute_constants()` as per #12: Changes a load immediate (`LDA #` or similar) somewhere before a given instruction. It replaces the literal number with a string constant or expression.
It can also either (a) Create all constants supplied, (b) Create just the constants used, or (c) Create no constants.

* Added my Chuckie Egg to the examples, which uses `substitute_constants()`.

* The CRTC register being written to can now also be identified by using this feature in acorn.py. There's an example of this in `local_labels.py`.

* expr(addr, s) can now take a `s` as a dictionary with integer keys and string values, similarly to the dictionary in substitute_constants(). The byte at the given address is replaced with an entry from the dictionary.

* Implements `is_assembler(s)` for all existing assemblers, also used in my Chuckie Egg example.

* Removed the dependency on third party python module `six`, which we were only using to identify string types and integer types. These are now regular functions in utils. 

* Fixed a few issues so now everything works properly in either python2 or python3. Fixed sorting issue with multiple label names at the same address.

* Updated documentation in README.md

### CODE REVIEW

**Comment by ZornsLemma** [comment]
Thanks Toby, I've been over this and it looks like a really nice piece of work! I've merged it to typed-addr, it seems to work fine for me but if you'd like to check it before I close this myself please do.

I found myself wondering if the subroutine_argument_finder_hooks functionality could be reimplemented in terms of the new constant substitution, e.g.:
```
trace.substitute_constant_list.append(SubConst("jsr osfile", 'a', osfile_a_enum, True))
```
but on reflection I think that doesn't really work, as the subroutine argument finder often wants to deal with multiple registers, and it may be that the correct constant for one register depends on the value in another, or something like that. So it's probably best to keep these separate, as they currently are.

**Comment by TobyLobster** [comment]
Yes, I had similar thoughts. I guess it could be generalised that instead of the dictionary, have a user callback that's called when 'a' (or whichever reg is specified) is about to be substituted, giving the addresses where A, X and Y load immediate values exist if available. Then the user could make their own expr() calls to set any of A,X,Y immediate values as appropriate.

A different but related improvement might be the ability to add inline comments, even when no immediate values are available, e.g.

    LDA room_data              ; A=sprite number
    LDX room_data+1            ; X=x-coordinate
    LDY room_data+2            ; Y=y-coordinate
    JSR plot_sprite

The CPU state would need to track the last instruction that changed each register.

But perhaps this feature just becomes overly complex?

**Comment by TobyLobster** [comment]
At some point, perhaps the master branch should be updated with the latest from typed-addr?

**Comment by ZornsLemma** [comment]
I can't help feeling a user callback instead of a dictionary for the constant substitution would make things more complex than necessary, although I haven't thought too deeply about it and if you feel inclined to try implementing this at some point then please don't let me put you off!

I like the inline comment idea, although I agree it is extra complexity - it probably wouldn't be that hard to track the extra information though, and this is the kind of thing that could be really helpful when getting to grips with some unfamiliar code under disassembly. Shall I raise an issue to track this idea?

**Comment by ZornsLemma** [comment]
If memory serves, the reason development moved off master is simply because I was doing all sorts of very experimental hackery to implement move() and the code was unreliable and I also hadn't updated the documentation. The code is obviously not all that experimental any more (although I think there are still quite a few rough edges on the move() functionality which I would like to tackle at some point but am also a bit scared to confront :-) ) and I think your recent pull requests have fixed up the documentation.

Are you aware of anything that still obviously needs fixing? If not I might just merge typed-addr onto master now. I suspect most py8dis users will be using the typed-addr branch anyway, as they'll have been following the thread on stardot, so it's not as if anyone is likely to be depending on the current master behaviour and be upset by a merge.

**Comment by TobyLobster** [comment]
> I like the inline comment idea, although I agree it is extra complexity - it probably wouldn't be that hard to track the extra information though, and this is the kind of thing that could be really helpful when getting to grips with some unfamiliar code under disassembly. Shall I raise an issue to track this idea?
Sure.

> Are you aware of anything that still obviously needs fixing? If not I might just merge typed-addr onto master now. I suspect most py8dis users will be using the typed-addr branch anyway, as they'll have been following the thread on stardot, so it's not as if anyone is likely to be depending on the current master behaviour and be upset by a merge.

Yes, this seems fine to me. It seems to be in a good working state. It feels like it warrants an update on Stardot to let people know.

**Comment by ZornsLemma** [comment]
Thanks Toby, I've now merged typed-addr to master and the 'go' test passes (although as usual I am hacking out the z88dk test as I don't have it installed).

Since all the changes are things you've worked on, would you like to do the post to stardot? You can say that the new features are on master as well as the typed-addr branch and that people should probably switch to using master from now on, and I'm sure you'll do a better job describing the new changes than I will. I'm happy to post if you'd prefer, though.

**Comment by TobyLobster** [comment]
Sure, I'll make a summary of the changes and post an update.

**Comment by ZornsLemma** [comment]
Thanks, I'll keep an eye on the forum!

**Pull request merged**
