### PR TITLE
Specify CPU as load parameter plus cycle reporting

### PR DESCRIPTION
**Pull request by TobyLobster**
* load() takes a CPU parameter which is a string, one of 6502,65C02,8080 or for the adventurous a user supplied CPU object. The old "import trace6502" style is gone. The assemblers are now classes.
* The cycle cost of each instruction can be reported (for 6502 and 65c02), disabled by default in config.
* The list of constants are sorted alphabetically and show decimal (not hex) values by default, enabled by default in config.
* The lists of constants and memory locations are aligned by their equals signs, to be tidy.
* A blank line is added after a data block and before code starts.
* Added a unix script to check all example files disassemble and reassemble correctly across all possible assemblers, producing the correct result
* Added a memorymanager.py to isolate some of that code.
* Workaround for an XA bug.
* Added ability to force a label to be 8 bit, even if the assembler can't work that out.
* Documented many of the major files via improved comments and README.md

### CODE REVIEW

**Comment by TobyLobster** [comment]
This should resolve both of the two issues (enhancements).

**Comment by TobyLobster** [comment]
Thanks. The test harness code does check the binary output by the assembler against the known good ".orig" binary file for each example and each assembler, showing the differences if any are found.

**Comment by TobyLobster** [comment]
I sneaked in another commit to this PR:

* Fix a bug where a CPU trace was being output for each data block.
* For label making: Comments for the `our_label_maker()` function have been added, and now renamed to `suggest_label_name()`. Only autogenerates a label if the user label maker hook function agrees to it. This fix means we get a more correct list of the autogenerated labels at the end of the output.
* Use ACME's `!to` command to save to a file like Beebasm does.

**Comment by ZornsLemma** [comment]
Thanks Toby! I was without internet yesterday so I couldn't merge this but I'm taking a look now.

I am seeing odd behaviour where beebasm refuses to assemble basic4.py's output because it contains things like:
```
assert sub_ca96b == 0xa96b
```
and beebasm doesn't like the 0x prefix to indicate hex. Do I have a strange build of beebasm or do you have a local patch which makes this work on your version?

I've "fixed" this in commit 244ccb6 on the typed-addr-merge branch, but that then breaks acme, because it doesn't seem to like:
```
!if (cb522) != $b522 {                                                           
    !error "Assertion failed: cb522 == $b522"                                    
}                                                                                
```
Adding brackets around the rhs of the != operator doesn't seem to help. I could hack round this by adding a special assert_hex() function for each assembler which does (Python) hex() for acme and generates a & prefix for beebasm, but it would be good to know what's going on here. Can you shed any light on this before I hack it?

I am also seeing an error rebuilding basic4.py's output on acme because of double-quote escaping:
```
Error - File build/basic4_acme.asm, line 8764 (Zone <untitled>): Garbage data at end of statement.
```
where the relevant line is:
```
    !text "\" at line \";"                                            ; b2ee: 22 20 61... " a
```
I am using:
```
$ acme --version
This is ACME, release 0.96.4 ("Fenchurch"), 1 Feb 2019
  Platform independent version.
```
I know there is a 0.97 "Zem" version of acme and upgrading might fix this, but do you think it's worth trying to support the older version? (Genuine question. If you don't, I'll upgrade.)

**Comment by TobyLobster** [comment]
I have a sneaking suspicion this is a python2 vs 3 thing. I have a fancy new Mac which no longer ships with python. So I do have python2 and 3 installed, but default to python3 since I'm having local difficulties with python2.

Anyway, I'm thinking that is why we may be getting slightly different results. 

In particular the asserts may be going wrong because we use the `hex()` function, but should be using `self.hex()` to force the use of the current class but perhaps for you it's using python's built in `hex()` function. It may help to rename this function to avoid confusion. I can look at this.

I'm using the later version of acme:

    $ acme --version
    This is ACME, release 0.97 ("Zem"), 4 Jul 2020
      Platform independent version.

But we should be able to support 0.96 I think. I'll downgrade and see what happens.

**Comment by ZornsLemma** [comment]
Thanks Toby. FWIW I am not sure it's Python 2 vs 3, as my "default" Python is 2 but your "go" test script explicitly invokes Python 3, so I will have tried both. But I may not have been paying full attention to this.

The self.hex() tweak is what I did on the typed-addr-merge branch and which then causes problems for acme, although I do find myself wondering if that's a bit of a red herring and it's really a 0.96-v-0.97 thing. If you're happy to try an experimental downgrade of acme I'll wait and see what you come up with.

**Comment by TobyLobster** [comment]
I think you are right. I get the same errors you do with acme 0.96. So acme 0.96 doesn't like embedding quotes. I found this documented in the changes for 0.97 https://sourceforge.net/p/acme-crossass/code-0/HEAD/tree/trunk/docs/Changes.txt

**Comment by TobyLobster** [comment]
I guess it would have to output this to be backwards compatible:

    !text 34, " at line ", 34, ";"                                            ; b2ee: 22 20 61... " a

Does that seem reasonable?

**Comment by TobyLobster** [comment]
Ok, I've pushed a fix for self.hex() where needed and acme 0.96 compatibility.

**Comment by ZornsLemma** [comment]
Thanks Toby, that looks good to me. Let me pull it to typed-addr-merge and see how I get on with it...

**Comment by ZornsLemma** [comment]
I've merged this to typed-addr now, thanks again for doing this! If you feel like giving the merged version a sanity check please do, I'll hold off closing this for a bit just in case and close it later if I don't hear from you.

**Comment by TobyLobster** [comment]
Small fix pushed for when a classification is split.

**Comment by TobyLobster** [comment]
Found when testing [starship_test](https://github.com/TobyLobster/starship_test) repo.

**Comment by ZornsLemma** [comment]
Thanks Toby, I've merged that to typed-addr now.

**Pull request merged**
