### PR TITLE
Subroutine() implemented, for better commentary around user and OS calls

### PR DESCRIPTION
**Pull request by TobyLobster**
The `subroutine()` command documents a subroutine, either an OS call or a user subroutine. All parameters other than the address are optional. User subroutines are commented before their definition, and also comments are automatically added wherever they are called, to document the parameters (this can be turned off for a subroutine if not wanted). There is a new example `subroutine_test` to show this feature for user subroutines.

I have used this feature in acorn.py to document several OS calls, but so far just focussing on those used in the example files. Clearly more of this could be done here, but this feels like a good start. A test example that exercises all code paths for each OS call would be useful, but for now this remains in the TODO column.

Also the examples/go script has a new option -x to make 'extra' files such as reports, symbol files etc.

### CODE REVIEW

**Comment by TobyLobster** [comment]
This implements #18

**Comment by ZornsLemma** [comment]
This is great stuff, Toby! The inline comments describing the behaviour of the OS calls feel like magic somehow. :-) It must have taken ages adding the explicit logic to handle all of these as well.

I have pulled your changes onto a new branch https://github.com/ZornsLemma/py8dis/tree/beef-up-cpu-state-tweaks in my own repo as I've made a few tweaks which I'd appreciate your thoughts on before I merge this to master:

- I noticed and fixed a bug (which I'm 99% sure existed beforehand) in make_increment()/make_decrement() where they would incorrectly persist any current N/Z flag state even if the value being incremented/decremented wasn't known.
- config.set_subroutine_{header,footer}() didn't have a "global" line in them so had no effect (at least on Python 2; I didn't try Python 3, but I suspect it's the same there)
- config.set_subroutine_header(None) causes the header to be entirely omitted, and ditto for ..._footer(). This is different from using set_subroutine_header("")  as that leaves a blank line.

I think there might be another small bug which I haven't fixed as I wanted to check with you first. I think regular_update() should set "previous_load_imm = None" in the 'O' case - do you agree? If you turn CPU state comments on and run dfs226.py, it says:
```
    lda #&0a                                                          ; 81d4: a9 0a       ..  A:0a X:-- Y:-- n---z-
    sta l00b0                                                         ; 81d6: 85 b0       ..  A:0a X:-- Y:-- n---z-
    lda l00bc                                                         ; 81d8: a5 bc       ..  A:0a X:-- Y:-- ------
```
That last line looks wrong - we don't know that A=&A at this point.

One small possible change might be to do "jmp print_hex_byte" instead of "jsr print_hex_byte:rts" in subroutine_test.asm, just as a test/demonstration of jmp subroutine calls instead of jsr subroutine calls.

As a future enhancement, I wonder if we should tweak the wording of some of the OS subroutine labels to be more explicit about the return values. For example, change "Check for EOF" to "Set C if EOF" (or "Set C iff EOF" if we're feeling pedantic :-) ).

Also as a possible future enhancement, I wonder if we might be able to use the "on exit" information for a subroutine to add inline comments to store operations after the subroutine call. For example, given:
```
subroutine(0x4022, "foo", on_exit={'a': 'open file handle count'})
```
we might generate:
```
jsr foo
sta &70 ; A=open file handle count
```
I think this is likely to be quite hard though, but if you think it seems reasonable I'll raise an enhancement issue for it. Given this, I wonder if the subroutine() example should be tweaked not to use "preserved" as an on exit comment - this is obviously a legitimate and desirable thing to document, *but* it wouldn't make so much sense if we start labelling store-after-subroutine using these values and maybe we shouldn't encourage this use. Maybe we'd just add an "on_exit_comment" dictionary to handle this hypothetical enhancement though, or something else entirely.

One potential downside of using the "optimistic" CPU state tracing in conjunction with the new subroutine-based labelling is that it might give slightly misleading comments in loops. For example, if we have:
```
ldx #5
.loop
jsr flush_buffer_x
dex
bpl loop
```
and we tell py8dis that X is a buffer number when flush_buffer_x is called, we might end up with:
```
ldx #collision_buffer
.loop
jsr flush_buffer_x ; flush collision buffer
dex
bpl loop
```
where the ldx # has had an expr() applied automatically and the jsr has had a comment attached, but the comment on the jsr doesn't apply to all executions of the loop, just the first. The ldx # annotation doesn't suffer from the same problem because the ldx # is outside the loop. I appreciate this is a bit contrived but I hope you see the point. I don't think this is a big deal and having the subroutine annotations is definitely a net win, but I do wonder if this is worth bearing in mind, and/or adding some sort of option to disable these comments selectively. This is potentially quite fiddly, I just wanted to make the observation.

**Comment by TobyLobster** [comment]
Yes I've taken a look through your changes and I think they are all correct, and the proposed fix for regular_update() does sound right to me too.

> One small possible change might be to do "jmp print_hex_byte"...

That sounds right.

> I wonder if we should tweak the wording of some of the OS subroutine labels to be more explicit about the return values

Yes. It can sometimes be difficult to summarise what a call does and also what it returns without ballooning the comment out, your example is good though. If we can get the post-subroutine comments working that may help also. 

Post subroutine comments will need special handling, but will be useful. Also (as you say) the `on_exit` structure needs to know the difference between "preserved" vs "file handle" style comments. Maybe we add brackets for comments that are not to be repeated elsewhere i.e. { "a": "(preserved)" }.

Getting post subroutine comments working for OS calls is one challenge further, since they will depend on the exact parameters to the subroutine, so would need to be generated by the hook routine itself. Maybe it returns an `on_exit` structure? It can return None for a regular subroutine in the default hook.

> if this is worth bearing in mind, and/or adding some sort of option to disable these comments selectively.

Maybe when we discover a loop we should clear the state at the start of the loop? That should cover a lot of cases, but maybe there is also a command, say `no_automatic_comment(addr)` for manual intervention?

I'm currently working through the rest of OSBYTE to document them, using an example that calls each OSBYTE routine in turn to exercise each code path through the hook function. This might take a while :-)

**Comment by ZornsLemma** [comment]
Thanks Toby. Do you want me to make the regular_update() change or shall I leave it for you, if you're making other changes as well?

Everything you say sounds sensible. I did just want to comment on the "loop" stuff though before I forget. I think no_automatic_comment() is probably the way to go; the problem with automatically clearing state at the start of a loop is that (if I understand correctly) it would stop us identifying things like the "ldx #" in my example as an opportunity to auto-generate a constant, as there'd be no state for the subroutine to operate on.

The OSBYTE project sounds quite epic, but I expect the results will be pretty impressive!

**Comment by TobyLobster** [comment]
> Do you want me to make the regular_update() change or shall I leave it for you, if you're making other changes as well?

Please go ahead, I'm basically just working on `acorn.py` at the moment.

Re: loops. Yes that's awkward. We could mark each instruction that's inside a loop as `no_automatic_comment()`, but I feel that might eliminate valid cases within the loop. Seems like manual `no_automatic_comment()` is the way to go then.

**Comment by ZornsLemma** [comment]
Thanks, I've pushed the change to regular_update() on my beef-up-cpu-state-tweaks branch; it looks like the incorrect CPU state I gave as an example was actually caused by self[reg].value not being set to None rather than previous_load_imm, so I've changed that as well. A quick look over the dfs226.py output with CPU state comments suggests this is working correctly.

My inclination is to merge this to master now, as it's a very useful change as-is, so let me know if you're still happy for me to do that or if you'd rather I wait until you've finished updating acorn.py.

**Comment by TobyLobster** [comment]
Yes, merging to master is useful. My changes will take a while longer.

**Comment by TobyLobster** [comment]
Actually, did I just push my latest stuff?

**Comment by TobyLobster** [comment]
That was an unintentional push by me, sorry, but should be OK. It's basically adding more OSBYTE cases, with an example os_calls.asm to test it.

**Comment by ZornsLemma** [comment]
Thanks Toby, as you say I still have the tweaked branch which doesn't include your latest stuff. As it sounds like you didn't really plan for me to merge your latest stuff, I've just merged the tweaked branch to master and pushed that. If you want me to merge the latest stuff now I'm happy to do that, it's your call.

**Comment by TobyLobster** [comment]
Ok, sounds good, let's hold off with the latest batch until I've done more.

**Pull request merged**
